apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: libapp
spec:
  limits:
  - max:
      cpu: 800m
      memory: 1Gi
    min:
      cpu: 200m
      memory: 500Mi
    type: Container