---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository for Debian Bullseye
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER }}"
    append: true
    groups: docker

- name: Reset SSH connection
  ansible.builtin.meta: reset_connection
