#designed to collect logs from both the system and Docker containers, process them through various pipeline stages, 
#and then send them to a Loki instance for storage and querying

server:
  http_listen_address: 0.0.0.0  #accept connection from any
  http_listen_port: 9080  #listen reqeusts in this port

positions:
  filename: /tmp/positions.yaml  #specifies the location of the file where Promtail will store its positions.

clients:
  - url: http://loki:3100/loki/api/v1/push #endpoint where Promtail will send the collected logs.

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost #from local machine
    labels:
      job: varlogs
      __path__: /var/log/*/*log

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs ##,,,<-
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output