apiVersion: v1
kind: Service
metadata:
  name: lib-service
  namespace: libapp
spec:
  type: LoadBalancer #external service to make it accessible by browser 
  selector:
    app: lib
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      #nodePort : 30100 #range of available ports from 30000 to 32767
 